# Generated by Django 5.1 on 2024-09-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itteam',
            name='expertise_areas',
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itteam',
            name='expertise_areas',
            field=models.ManyToManyField(related_name='teams', to='api.requestservice'),
        ),
    ]
