# Generated by Django 5.1 on 2024-09-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_itteam_expertise_areas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='requestservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='request_description',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='request_status',
        ),
        migrations.AlterField(
            model_name='itteam',
            name='expertise_areas',
            field=models.ManyToManyField(related_name='teams', to='api.expertisearea'),
        ),
    ]
