# Generated by Django 5.1 on 2024-09-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_expertisearea_remove_requestservice_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertisearea',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itteam',
            name='expertise_areas',
            field=models.ManyToManyField(to='api.expertisearea'),
        ),
    ]
